name: Docker Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      - name: Build push Heroku		
        uses: docker/build-push-action@v2 	
        with:		
          username: ${{ secrets.HEROKU_USERNAME }}		
          password: ${{ secrets.HEROKU_API_KEY }}		
          registry: registry.heroku.com
          repository: docs-io/web
          tags: latest
      - name: Build push Github Packages
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
          tags: latest
